---
abstract: 'Utility to interface with Akamai''s API '
author:
  - 'John Goulah  <jgoulah@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Akamai
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::SSLeay: 0.57
  Digest::MD5: 2.36
  Moose: 0.45
  MooseX::AttributeHelpers: 0.09
  MooseX::Types: 0.04
  SOAP::Lite: 0.710.05
  Text::Tabs: 0
tests: t/*.t
version: 0.12
